openapi: 3.0.0
info:
  title: My Express API
  version: 1.0.0
paths:
  /api/example:
    get:
      summary: Example API
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                message: Hello, Swagger!
